### ISSUE TITLE
add new CS resources

### ISSUE THREAD

**Issue by dreamtocode** [dreamtocode/awesome-resources#4]
If there is great sites that you use to learn from please add it so everyone will know it

**Comment by Toughee** [comment]
I have a few that I can add.  Is it okay if I contribute?

**Comment by dreamtocode** [comment]
Hi @Toughee 
Yes, please read this: https://github.com/dreamtocode/awesome-resources#contributing 
Have a great day!

**Comment by Toughee** [comment]
I added the resources in the young and advanced learners section.  Trying to make a pull request, but it won't let me.  You can see the changes in my fork.

https://github.com/Toughee/awesome-resources

**Comment by dreamtocode** [comment]
Hello @Toughee 
What do you mean it won't let you?
Do not remove resources, only add it if you think it is awesome. 
This time I will not merge it because you removed some resources. Anyway you can create new fork and edit it than send pull request. 
Have a great day!

**Comment by dreamtocode** [comment]
Hi again @Toughee 
Thanks for the email. Check it now, I just updated our resources and thanks again for recommendation. People like you make our shared resources even better and interesting.
Have a happy day!
